//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPARCHIPERCEPTRON.Présentation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class frmAnalyseEcriture {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal frmAnalyseEcriture() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TPARCHIPERCEPTRON.Présentation.frmAnalyseEcriture", typeof(frmAnalyseEcriture).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode btnEffacer_ImeMode {
            get {
                object obj = ResourceManager.GetObject("btnEffacer.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=268,Y=36}.
        /// </summary>
        public static System.Drawing.Point btnEffacer_Location {
            get {
                object obj = ResourceManager.GetObject("btnEffacer.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size btnEffacer_Size {
            get {
                object obj = ResourceManager.GetObject("btnEffacer.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int btnEffacer_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnEffacer.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer.
        /// </summary>
        public static string btnEffacer_Text {
            get {
                return ResourceManager.GetString("btnEffacer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode btnEntrainement_ImeMode {
            get {
                object obj = ResourceManager.GetObject("btnEntrainement.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=253,Y=20}.
        /// </summary>
        public static System.Drawing.Point btnEntrainement_Location {
            get {
                object obj = ResourceManager.GetObject("btnEntrainement.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=106, Height=47}.
        /// </summary>
        public static System.Drawing.Size btnEntrainement_Size {
            get {
                object obj = ResourceManager.GetObject("btnEntrainement.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int btnEntrainement_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnEntrainement.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrainement.
        /// </summary>
        public static string btnEntrainement_Text {
            get {
                return ResourceManager.GetString("btnEntrainement.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode btnTest_ImeMode {
            get {
                object obj = ResourceManager.GetObject("btnTest.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=253,Y=20}.
        /// </summary>
        public static System.Drawing.Point btnTest_Location {
            get {
                object obj = ResourceManager.GetObject("btnTest.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=106, Height=47}.
        /// </summary>
        public static System.Drawing.Size btnTest_Size {
            get {
                object obj = ResourceManager.GetObject("btnTest.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int btnTest_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnTest.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string btnTest_Text {
            get {
                return ResourceManager.GetString("btnTest.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=268,Y=77}.
        /// </summary>
        public static System.Drawing.Point btnTestConf_Location {
            get {
                object obj = ResourceManager.GetObject("btnTestConf.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size btnTestConf_Size {
            get {
                object obj = ResourceManager.GetObject("btnTestConf.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int btnTestConf_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnTestConf.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestConfFile.
        /// </summary>
        public static string btnTestConf_Text {
            get {
                return ResourceManager.GetString("btnTestConf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=8,Y=36}.
        /// </summary>
        public static System.Drawing.Point grpDessinEntrainement_Location {
            get {
                object obj = ResourceManager.GetObject("grpDessinEntrainement.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=366, Height=138}.
        /// </summary>
        public static System.Drawing.Size grpDessinEntrainement_Size {
            get {
                object obj = ResourceManager.GetObject("grpDessinEntrainement.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        public static int grpDessinEntrainement_TabIndex {
            get {
                object obj = ResourceManager.GetObject("grpDessinEntrainement.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone de dessin.
        /// </summary>
        public static string grpDessinEntrainement_Text {
            get {
                return ResourceManager.GetString("grpDessinEntrainement.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=9,Y=180}.
        /// </summary>
        public static System.Drawing.Point grpEntrainement_Location {
            get {
                object obj = ResourceManager.GetObject("grpEntrainement.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=365, Height=79}.
        /// </summary>
        public static System.Drawing.Size grpEntrainement_Size {
            get {
                object obj = ResourceManager.GetObject("grpEntrainement.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int grpEntrainement_TabIndex {
            get {
                object obj = ResourceManager.GetObject("grpEntrainement.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrainement.
        /// </summary>
        public static string grpEntrainement_Text {
            get {
                return ResourceManager.GetString("grpEntrainement.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=9,Y=265}.
        /// </summary>
        public static System.Drawing.Point grpTests_Location {
            get {
                object obj = ResourceManager.GetObject("grpTests.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=365, Height=79}.
        /// </summary>
        public static System.Drawing.Size grpTests_Size {
            get {
                object obj = ResourceManager.GetObject("grpTests.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        public static int grpTests_TabIndex {
            get {
                object obj = ResourceManager.GetObject("grpTests.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        public static string grpTests_Text {
            get {
                return ResourceManager.GetString("grpTests.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool lblValeurEntraine_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblValeurEntraine.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode lblValeurEntraine_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lblValeurEntraine.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=7,Y=40}.
        /// </summary>
        public static System.Drawing.Point lblValeurEntraine_Location {
            get {
                object obj = ResourceManager.GetObject("lblValeurEntraine.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=90, Height=13}.
        /// </summary>
        public static System.Drawing.Size lblValeurEntraine_Size {
            get {
                object obj = ResourceManager.GetObject("lblValeurEntraine.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        public static int lblValeurEntraine_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblValeurEntraine.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur entrainée :.
        /// </summary>
        public static string lblValeurEntraine_Text {
            get {
                return ResourceManager.GetString("lblValeurEntraine.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool lblValeurTestee_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblValeurTestee.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode lblValeurTestee_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lblValeurTestee.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=7,Y=40}.
        /// </summary>
        public static System.Drawing.Point lblValeurTestee_Location {
            get {
                object obj = ResourceManager.GetObject("lblValeurTestee.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=13}.
        /// </summary>
        public static System.Drawing.Size lblValeurTestee_Size {
            get {
                object obj = ResourceManager.GetObject("lblValeurTestee.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        public static int lblValeurTestee_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblValeurTestee.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur testée :.
        /// </summary>
        public static string lblValeurTestee_Text {
            get {
                return ResourceManager.GetString("lblValeurTestee.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point mnuPrincipal_Location {
            get {
                object obj = ResourceManager.GetObject("mnuPrincipal.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=386, Height=24}.
        /// </summary>
        public static System.Drawing.Size mnuPrincipal_Size {
            get {
                object obj = ResourceManager.GetObject("mnuPrincipal.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        public static int mnuPrincipal_TabIndex {
            get {
                object obj = ResourceManager.GetObject("mnuPrincipal.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mnuPrincipale.
        /// </summary>
        public static string mnuPrincipal_Text {
            get {
                return ResourceManager.GetString("mnuPrincipal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        public static System.Drawing.Point mnuPrincipal_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("mnuPrincipal.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool rdManual_AutoSize {
            get {
                object obj = ResourceManager.GetObject("rdManual.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode rdManual_ImeMode {
            get {
                object obj = ResourceManager.GetObject("rdManual.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=19}.
        /// </summary>
        public static System.Drawing.Point rdManual_Location {
            get {
                object obj = ResourceManager.GetObject("rdManual.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=60, Height=17}.
        /// </summary>
        public static System.Drawing.Size rdManual_Size {
            get {
                object obj = ResourceManager.GetObject("rdManual.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        public static int rdManual_TabIndex {
            get {
                object obj = ResourceManager.GetObject("rdManual.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manuel.
        /// </summary>
        public static string rdManual_Text {
            get {
                return ResourceManager.GetString("rdManual.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool rdUseBD_AutoSize {
            get {
                object obj = ResourceManager.GetObject("rdUseBD.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode rdUseBD_ImeMode {
            get {
                object obj = ResourceManager.GetObject("rdUseBD.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=42}.
        /// </summary>
        public static System.Drawing.Point rdUseBD_Location {
            get {
                object obj = ResourceManager.GetObject("rdUseBD.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=118, Height=17}.
        /// </summary>
        public static System.Drawing.Size rdUseBD_Size {
            get {
                object obj = ResourceManager.GetObject("rdUseBD.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int rdUseBD_TabIndex {
            get {
                object obj = ResourceManager.GetObject("rdUseBD.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utiliser données BD.
        /// </summary>
        public static string rdUseBD_Text {
            get {
                return ResourceManager.GetString("rdUseBD.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool rdUseMNIST_AutoSize {
            get {
                object obj = ResourceManager.GetObject("rdUseMNIST.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode rdUseMNIST_ImeMode {
            get {
                object obj = ResourceManager.GetObject("rdUseMNIST.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=65}.
        /// </summary>
        public static System.Drawing.Point rdUseMNIST_Location {
            get {
                object obj = ResourceManager.GetObject("rdUseMNIST.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=137, Height=17}.
        /// </summary>
        public static System.Drawing.Size rdUseMNIST_Size {
            get {
                object obj = ResourceManager.GetObject("rdUseMNIST.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        public static int rdUseMNIST_TabIndex {
            get {
                object obj = ResourceManager.GetObject("rdUseMNIST.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utiliser données MNIST.
        /// </summary>
        public static string rdUseMNIST_Text {
            get {
                return ResourceManager.GetString("rdUseMNIST.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=119, Height=20}.
        /// </summary>
        public static System.Drawing.Size tsmiAfficherDessins_Size {
            get {
                object obj = ResourceManager.GetObject("tsmiAfficherDessins.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les dessins.
        /// </summary>
        public static string tsmiAfficherDessins_Text {
            get {
                return ResourceManager.GetString("tsmiAfficherDessins.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=162, Height=22}.
        /// </summary>
        public static System.Drawing.Size tsmiBaseDeDonnées_Size {
            get {
                object obj = ResourceManager.GetObject("tsmiBaseDeDonnées.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base de données.
        /// </summary>
        public static string tsmiBaseDeDonnées_Text {
            get {
                return ResourceManager.GetString("tsmiBaseDeDonnées.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=162, Height=22}.
        /// </summary>
        public static System.Drawing.Size tsmiFichier_Size {
            get {
                object obj = ResourceManager.GetObject("tsmiFichier.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier.
        /// </summary>
        public static string tsmiFichier_Text {
            get {
                return ResourceManager.GetString("tsmiFichier.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=58, Height=20}.
        /// </summary>
        public static System.Drawing.Size tsmiLangue_Size {
            get {
                object obj = ResourceManager.GetObject("tsmiLangue.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        public static string tsmiLangue_Text {
            get {
                return ResourceManager.GetString("tsmiLangue.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=84, Height=20}.
        /// </summary>
        public static System.Drawing.Size tsmiSauvegarder_Size {
            get {
                object obj = ResourceManager.GetObject("tsmiSauvegarder.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string tsmiSauvegarder_Text {
            get {
                return ResourceManager.GetString("tsmiSauvegarder.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=8,Y=350}.
        /// </summary>
        public static System.Drawing.Point txtConsole_Location {
            get {
                object obj = ResourceManager.GetObject("txtConsole.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool txtConsole_Multiline {
            get {
                object obj = ResourceManager.GetObject("txtConsole.Multiline", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=366, Height=185}.
        /// </summary>
        public static System.Drawing.Size txtConsole_Size {
            get {
                object obj = ResourceManager.GetObject("txtConsole.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int txtConsole_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtConsole.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=103,Y=37}.
        /// </summary>
        public static System.Drawing.Point txtValeurEntrainee_Location {
            get {
                object obj = ResourceManager.GetObject("txtValeurEntrainee.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=100, Height=20}.
        /// </summary>
        public static System.Drawing.Size txtValeurEntrainee_Size {
            get {
                object obj = ResourceManager.GetObject("txtValeurEntrainee.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int txtValeurEntrainee_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtValeurEntrainee.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=103,Y=37}.
        /// </summary>
        public static System.Drawing.Point txtValeurTestee_Location {
            get {
                object obj = ResourceManager.GetObject("txtValeurTestee.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=100, Height=20}.
        /// </summary>
        public static System.Drawing.Size txtValeurTestee_Size {
            get {
                object obj = ResourceManager.GetObject("txtValeurTestee.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int txtValeurTestee_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtValeurTestee.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=148,Y=36}.
        /// </summary>
        public static System.Drawing.Point ucDessin_Location {
            get {
                object obj = ResourceManager.GetObject("ucDessin.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=64, Height=64}.
        /// </summary>
        public static System.Drawing.Size ucDessin_Size {
            get {
                object obj = ResourceManager.GetObject("ucDessin.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int ucDessin_TabIndex {
            get {
                object obj = ResourceManager.GetObject("ucDessin.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
