//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPARCHIPERCEPTRON
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerceptronModel
    {
        public int PerceptronID { get; set; }
        public string LettresPerceptron { get; set; }
        public string BitArray { get; set; }
        public int Hauteur { get; set; }
        public int Largeur { get; set; }
    }
}
